### ISSUE TITLE
Failed to install argocd

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#19]
## Describe the Bug

Got **unexpected EOF** error when using dsm to install argocd.

## How to Reproduce

1. Prepare config.yaml and put it in _/tmp/config.yaml_
```yaml
---
tools:
- name: argocd
  version: 0.0.1
  options:
    repo:
      name: argo
      url: https://argoproj.github.io/argo-helm
    chart:
      name: argo/argo-cd
      release_name: argocd
      namespace: argocd
      create_namespace: False
```
2. Execute `./dsm install -f /tmp/config.yaml`
3. Got unexpected EOF error.

## Screenshots

<img width="1228" alt="截屏2021-11-26 上午10 15 49" src="https://user-images.githubusercontent.com/18692628/143516759-e40f7526-68ec-47f3-b8b1-e7e00780c0c0.png">
