### ISSUE TITLE
Bug: extra field with helm-style plugins state

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#219]
## Describe the Bug

extra field:

```yaml
      daemonsets: []
      statefulsets: []
```

devstream.state

```yaml
argocd-dev_argocd:
  name: argocd-dev
  plugin:
    kind: argocd
    version: 0.0.2
  options:
    chart:
      chart_name: argo/argo-cd
      namespace: argocd
      release_name: argocd
      timeout: 5m
      upgradeCRDs: true
      wait: false
    create_namespace: true
    repo:
      name: argo
      url: https://argoproj.github.io/argo-helm
  resource:
    workflows:
      deployments:
        - name: argocd-application-controller
          ready: true
        - name: argocd-dex-server
          ready: true
        - name: argocd-redis
          ready: true
        - name: argocd-repo-server
          ready: true
        - name: argocd-server
          ready: true
      daemonsets: []
      statefulsets: []
```

## Screenshots

![image](https://user-images.githubusercontent.com/18692628/155257589-4a4a524a-c5d3-41f3-9b58-c9fafb668cd5.png)
