### ISSUE TITLE
Bug(`github-repo-scaffolding-golang`): the `branch` param does NOT take effect.

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#237]
## Describe the Bug

The config.yaml I used:

```yaml
tools:
  - name: crbot
    plugin:
      kind: github-repo-scaffolding-golang
      version: 0.2.0
    options:
      owner: daniel-hutao
      repo: crbot
      branch: master
      image_repo: exploitht/crbot
```

After I executed the command `./dtm-darwin-arm64 apply -y -f config-github-reposcaffolding-golang.yaml --debug`, I got the repo like below:

![image](https://user-images.githubusercontent.com/18692628/155825605-04e0c2f9-4825-4e61-8976-bd63d6b452ae.png)

At this time, you can see that the branch is `main`, not the `master` specified in the configuration file.
