### ISSUE TITLE
`dtm verify` results show that some tools are not healthy, but can't get more detail

### ISSUE THREAD

**Issue by imxw** [merico-dev/stream#252]
## Describe the Bug

dtm version: dtm-darwin-arm64 0.2.0 
OS: MacOS  M1
config file: 
```yaml
---
tools:
- name: golang-demo-repo
  plugin:
    kind: github-repo-scaffolding-golang
    version: 0.2.0
  options:
    owner: ironcore864
    # will also be used as application name
    repo: golang-demo
    branch: main
    image_repo: ironcore864/golang-demo
- name: golang-demo-app
  plugin:
    kind: githubactions-golang
    version: 0.2.0
  options:
    owner: ironcore864
    repo: golang-demo
    language:
      name: go
      version: "1.17"
    branch: main
    build:
      enable: True
    test:
      enable: True
      coverage:
        enable: True
    docker:
      enable: True
- name: go-hello-world-gitlab-ci
  plugin:
    kind: gitlabci-golang
    version: 0.2.0
  options:
    pathWithNamespace: ironcore864/golang-demo
    branch: main
- name: devlake
  plugin:
    kind: devlake
    version: 0.2.0
```

## How to Reproduce

```bash
$ dtm init
$ dtm verify
```

## Screenshots

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/16207029/156316235-9504f114-d27a-470b-86bb-d14087354eac.png">
