### ISSUE TITLE
Bug(argocdapp): crd isn't a namespaced resource

### ISSUE THREAD

**Issue by daniel-hutao** [merico-dev/stream#257]
## Describe the Bug

![image](https://user-images.githubusercontent.com/18692628/156479299-d4870bb3-fc31-4906-bdba-d090a2d3029a.png)

config.yaml

```yaml
    options:
      # information on the ArgoCD application
      app:
        # name of the ArgoCD application
        name: hello
        # where the ArgoCD application CRD will be created
        namespace: argocd
```
